#!/usr/bin/env bash
# Install nginx
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo "Hello World!" > /var/www/html/index.nginx-derbian.html
sudo service nginx start
