#!/usr/bin/env bash
# Install nginx
apt-get -y upgrade
apt-get -y install nginx
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
