#!/usr/bin/env bash
# Install nginx
sudo apt- get -y update
sudo apt-get install -y nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
service nginx restart

