#!/usr/bin/env bash
# This displayes 1 to 20 with additions to 
# 4, 9 and 17

i=1
while [ $i -le 20 ]
do

	case $i in 
		4)
			echo "bad luck from China"
			;;
		
		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;

		*) echo "$i"

	esac
	(( i++ ))
done
