#!/usr/bin/env bash
# Fix container so that Nginx is running as user nginx
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
